sudo: false

language: php

branches:
  except:
    - /^release-\d+\.\d+\.\d+.*$/
    - /^ghgfk-.*$/

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-escaper
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-escaper.git
    - secure: "DYHr29FYrnmlacO6/CUBpVaCHeDjQbLj32fEmtL1JsMtgOfAMv8R5DMppjRzyFPmCGRR6sTOg6p7h+DCfTi4BvKDFHRe3WiYn55HzWgsC8kgpmETQwrnBsR94yjb+vsSc4Jy705BEicmafAyg8utOC3R8onkr/jR7u0HaOOCHEiMDPRFtnhEl2Ta3WckWBEhYwhjAVIYo03+xj9o8aghQmQdumidryzGSOhiAca/g86zMQt4u1MH7QmorXdFirymP6u4bz9k47tJjguoKQrovwokwJqSh6R/tsH2uQ+NduAt6y90DIcYmO4vV8Xd6dg3yewTeb5uxh6yntvxFsVq6qNQhCtK8FRoIIgXlvCG5EmwX2d4OkuASDRPhJEvp815LJ4/5IDHq6a7lkFyQ4oxNXI4rFh6VDYe+IyEtESDWepi+P5QV2xvsygvcd62JtVeGtzd8kUssytjXO/nyRSRuXueBHY0gNyiz6IHASzFcpgHzwBzRxZZfbs3d7iY2GzfXRvILyP/Jd5Rj8pFsiTJFs0LpHnseIZJfSu43LzzSRl9YRzfizNDNFUOa44dc2bH2/Fjqb2qRyG1sxYF8Nm5oSs38ePxaQZSept03FrUMJEVNpWitcKesvom4pD7bmmlTx55GccF+VvOWQb7InXZppWOY64UcwNWgi2jWA9n9ok="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls ; fi

install:
  - travis_retry composer install --no-interaction --ignore-platform-reqs

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/phpunit --coverage-clover clover.xml ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then ./vendor/bin/phpunit ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then ./vendor/bin/coveralls ; fi

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#zftalk.dev"
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: "W9cqFyRSVI3YVOB8WAsL6RAHaWX0Eu+P51v9qI3GUeZYlKoKs7Y1HDZ6K3afwzdOTQ8gdZAWjE98fkYtdcqakfLrsrQsxCW+IXvY97djrdG3W8d51FnlpbnFz10FHiT+D7a2yBCLLTDbuomNxhMFvgkdZYUXkPs4zPiGTwTntw22RM3FM1Yfak7Uqih0S+lzOaSuQsuo7GAvLV6Yzv9xBOZp7fnzK7EQtKp5btBGta4SD6KQOB4DL/sUW202pCVzghzsy0HtAkJmOSk2vGaMRI3iW9JZpRfkZKpZesRFA+BHvwDwlxD8T2TSOjZe89Bpb3Fa4u86aXVLUae9zVS8IXVplZbzm+4bmqTfmXslLdD79MUnYhn4Vpd8fJCKCaF6+cr0fGCnGoERiibqaMzhSxlVlhN8jRaC+5cwRtJTn6T5iB9aN+hzhJxVKkV7QUMA9NUr1Kd27dqfgO07gC4FDOxTS+xUfa+OA8HBOzGblNjQG2q1F1FPJkqt1csw1+A5l/yPBRHNsYZBg3SUKmSVYp+SmRDWRl7wgzH8FXbmccmbnLXwqpIiZ/KdjqtfXhKX2hpLOHml+3y7+t+AKWDlncqclot7x0DfJPeg3gEsgRc1vd0mlGB9t86RkoInK+MuVeyS8J9Ukon/g3Fq4SBgG/fMJpWD4/rvfzRu9Ilz1HQ="
    on_success: change
    on_failure: always
